In [14]:
import tensorflow as tf
import numpy as np
from scipy.signal import convolve2d
from tensorflow import keras

In [105]:
mat_size = 10
matrix = np.zeros((mat_size, mat_size)).astype(np.float32)
for x in range(3,6):
    for y in range(3,6):
        matrix[x,y] = 1

kernel = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]).astype(np.float32)
kernel = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,9]
]).astype(np.float32)

print("====== np.convolve2d")
np_conv = convolve2d(matrix, kernel, mode="valid")
print("shape:", np_conv.shape)
print(np_conv)

def kernel_init_l1(shape, dtype=None):
    print("kernel_initializer shape:", shape)
    return (tf.reshape(tf.constant(np.rot90(kernel,2), dtype=dtype), (3, 3, 1, 1)))

print("====== keras Conv2D")
keras_x = tf.constant(np.expand_dims(np.expand_dims(matrix, axis=0), axis=3))
layer = keras.layers.Conv2D(1, 3, activation="relu", 
                            padding="valid",
                            dilation_rate=(2,2),  # --- dilation rate
                            kernel_initializer=kernel_init_l1)
keras_y = layer(keras_x)
print("kernel:", np.squeeze(np.array(layer.weights)))
print("shape:", keras_y.shape)
print(np.squeeze(np.array(keras_y)))

# print(kernel_init_l1((3,3,1,1), tf.float32).shape)

====== np.convolve2d
shape: (8, 8)
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  2.  1.  0.  0.]
 [ 0.  2.  4.  6.  4.  2.  0.  0.]
 [ 0.  3.  6. 17. 14. 11.  0.  0.]
 [ 0.  2.  4. 14. 12. 10.  0.  0.]
 [ 0.  1.  2. 11. 10.  9.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
====== keras Conv2D
kernel_initializer shape: (3, 3, 1, 1)
kernel: [<tf.Variable 'conv2d_77/kernel:0' shape=(3, 3, 1, 1) dtype=float32, numpy=
array([[[[9.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]],

        [[1.]]]], dtype=float32)>
 <tf.Variable 'conv2d_77/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]
shape: (1, 6, 6, 1)
[[ 1.  2.  1.  2.  1.  1.]
 [ 2.  4.  2.  4.  2.  2.]
 [ 1.  2.  1.  2.  1.  1.]
 [ 2.  4.  2. 12. 10. 10.]
 [ 1.  2.  1. 10.  9.  9.]
 [ 1.  2.  1. 10.  9.  9.]]
