In [14]:
import tensorflow as tf
import numpy as np

from tensorflow.train  import BytesList, FloatList, Int64List
from tensorflow.train  import Example, Features, Feature


In [84]:
f_name = "my_data.tfrecord"
NUM_SAMPLES=10

with tf.io.TFRecordWriter(f_name) as f:
    for idx in tf.range(NUM_SAMPLES):

        feature = {
            "label": Feature(int64_list=Int64List(value=[1])),
            "ct": Feature(float_list=tf.train.FloatList(value=tf.random.normal([15]))),
        }

        example_proto = tf.train.Example(features = tf.train.Features(feature=feature))
        f.write(example_proto.SerializeToString())

    

In [87]:
feature_description = {
    "label": tf.io.FixedLenFeature([], tf.int64, default_value=0),
#     "ct": tf.io.FixedLenFeature([30], tf.float32, default_value=0),
    "ct": tf.io.VarLenFeature(tf.float32),
}

def parse_tfrecord(raw_record):
    return tf.io.parse_single_example(raw_record, feature_description)

for idx, record in enumerate(tf.data.TFRecordDataset([f_name, "my_data2.tfrecord"]).map(parse_tfrecord).batch(1)):
    print(idx, ")")
    print(record["label"], " -> ", record["ct"].values)


0 )
tf.Tensor([1], shape=(1,), dtype=int64)  ->  tf.Tensor(
[-0.00642292 -0.99663174 -1.4355795   0.12715252 -1.279885    1.0910966
  0.08595318 -0.17158575  1.9106659  -0.5452891  -1.0393394   0.5248868
 -0.00637967  0.23857222  0.47796246], shape=(15,), dtype=float32)
1 )
tf.Tensor([1], shape=(1,), dtype=int64)  ->  tf.Tensor(
[ 0.1261019  -0.6203369  -1.7718145  -0.27203864 -0.08258183  0.8969477
 -0.14569141 -1.0970638   0.76185274 -0.6345727  -0.19126001 -0.73333883
  1.0629454  -1.802514    1.2664388 ], shape=(15,), dtype=float32)
2 )
tf.Tensor([1], shape=(1,), dtype=int64)  ->  tf.Tensor(
[ 0.0957901  -0.22052959 -0.624276    0.14625488  1.0514182   1.2331035
  0.47668672 -1.0801736  -0.52799463  1.6421394  -0.89803255 -0.48218137
  0.01968126 -1.342721   -0.10588992], shape=(15,), dtype=float32)
3 )
tf.Tensor([1], shape=(1,), dtype=int64)  ->  tf.Tensor(
[-1.4553695   0.9790592   0.21012941 -0.06242161 -0.42905945  1.5689538
  1.0204804   2.2992284   1.4527656   1.8259331  -0.0