In [1]:
import numpy as np
import nibabel as nib

In [17]:
img = nib.load("/docs/src/kt/nii/DEMIN_A.S.__3__20190426153742.nii")
print("img shape:", img.shape)
print("img.affine.shape", img.affine.shape)
print("img.affine\n", img.affine)

img shape: (512, 512, 701)
img.affine.shape (4, 4)
img.affine
 [[-9.30000007e-01 -0.00000000e+00  0.00000000e+00  2.37815002e+02]
 [ 0.00000000e+00  9.30000007e-01  0.00000000e+00 -2.37414215e+02]
 [ 0.00000000e+00  0.00000000e+00  7.99926758e-01 -1.43844873e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [18]:
data = img.get_fdata()
print("data.shape:", data.shape)
print(data[1,1,1])

data.shape: (512, 512, 701)
-2048.0


In [23]:
data = np.ones((32, 32, 15), dtype=np.int16)
img = nib.Nifti1Image(data, np.eye(4))
nib.save(img, "123.nii")