In [2]:
import numpy

In [4]:
numpy.binary_repr(231)

'11100111'

In [5]:
numpy.add(8, 8.5)

16.5

In [6]:
def NN(m1, m2, w1, w2, bias):
    z = m1 * w1 + m2 * w2 + bias;
    return sigmoid(z)

def sigmoid(x):
    return 1 / (1 + numpy.exp(-x))

In [8]:
w1  = numpy.random.randn() * 2 - 1
w2  = numpy.random.randn() * 2 - 1
bias= numpy.random.randn() * 2 - 1


In [10]:
w1

-4.171509743668095

In [12]:
NN(4, 1.5, w1, w2, bias)

5.803747190316474e-09

In [14]:
import os;
os.system("say 123")

1

In [15]:
def cost(b):
    return(b -4)**2

In [16]:
def num_slope(b):
    h = 0.0001
    return (cost(b+h) - cost(b))/h

In [18]:
num_slope(4)

9.999999999953388e-05

In [19]:
def slope(b):
    return 2 * (b - 4)

In [20]:
num_slope(3)

-1.9999000000037181

In [21]:
slope(3)

-2

In [89]:
b = b - 0.1*slope(b)
print(b)

4.000000502168139


In [24]:
b = 5

In [90]:
for i in range(5):
    print(i)

0
1
2
3
4


In [92]:
range(3)

range(0, 3)

In [93]:
range(5)

range(0, 5)

In [99]:
for i in ['John', 1, '0']:
    print(i)

John
1
0


In [12]:
import numpy as np

arr = np.arange(10)

In [13]:
binary_arr = np.array(arr > 5, dtype=np.int8)

In [14]:
from skimage import measure

In [15]:
labels = measure.label(binary_arr)
labels

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64)

In [48]:
arr1 = np.array(np.eye(5)*5, dtype=np.int8)
arr1[0, :] = 7
arr1[:, 3] = 9
print(arr1)
print(measure.label(arr1))
print(measure.label(arr1, connectivity=1))
print(measure.label(arr1, connectivity=2))


[[7 7 7 9 7]
 [0 5 0 9 0]
 [0 0 5 9 0]
 [0 0 0 9 0]
 [0 0 0 9 5]]
[[1 1 1 2 3]
 [0 4 0 2 0]
 [0 0 4 2 0]
 [0 0 0 2 0]
 [0 0 0 2 5]]
[[1 1 1 2 3]
 [0 4 0 2 0]
 [0 0 5 2 0]
 [0 0 0 2 0]
 [0 0 0 2 6]]
[[1 1 1 2 3]
 [0 4 0 2 0]
 [0 0 4 2 0]
 [0 0 0 2 0]
 [0 0 0 2 5]]


In [47]:
vals, counts = np.unique(arr1, return_counts=True)
print("vals: ",vals)
print("counts: ", counts)

print("largest label volume", vals[np.argmax(counts)])

vals:  [ 7  9 40 45]
counts:  [ 4  5 13  3]
largest label volume 40
